### PR TITLE
Force Arena 0 when fighting Kreissack in 1 player mode - with corrections

### PR DESCRIPTION
**Pull request by gdeda**
ref to #292 
Sorry, did a little mess with github...
Now with corrections suggested, and a new branch from my fork :)

On a side note, should PILOT_KREISSACK be applied also on line 270 for better readability?
else if (player2->pilot_id == 10 && settings_get()->gameplay.difficulty < 2)

### CODE REVIEW

**Comment by katajakasa** [comment]
Yes, PILOT_KREISSACK would probably be a good thing there too. If you have the time and energy, feel free to add it. Otherwise we'll just merge :)

**Comment by Vagabond** [comment]
Yeah, and you don't need to open a new PR, you can just push more commits to this branch (or squash and force-push).

**Comment by Vagabond** [comment]
There's also a one on line 442 that refers to kreissack. heh.

**Comment by gdeda** [comment]
Done, tested, looks like nothing is broken... :)

**Pull request merged**
