### PR TITLE
give apple OpenAL include better default location

### PR DESCRIPTION
**Pull request by Sharnw**
Hey mate,

Had to make a fix to build with OpenAL on osx. No probs if this is unnecessary but would love to contribute.

You're doing amazing work. Cheers!

### CODE REVIEW

**Comment by ericmhalvorsen** [comment]
Saw the same issue, this fixed it for me. Compiled OpenAL from source downloaded from this link: http://kcat.strangesoft.net/openal.html

@Vagabond Any recommended method for MacOSX to avoid this issue?

**Comment by Vagabond** [comment]
I think it depends on how you installed openal, I think I installed it from macports or from homebrew.

**Comment by Vagabond** [comment]
I'm not sure how to solve this properly, maybe we can use cmake to look for the header files?

**Comment by katajakasa** [comment]
I wouldn't go changing the default seek location; i'd rather modify the cmake script to look from different places, indeed. Or, I'd rather accept a patch that does that :P

**Comment by katajakasa** [comment]
Possibly fixed in master with commit 23e5aa96bed9be006fac66e95bc2bb6268759213
Please test.

**Pull request closed without merging**
